name: "Build and upload to Cachix"
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: debarchito
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build Blender with CUDA enabled
        run: nix build .#blender
      - name: Upload Blender to Cachix
        run: cachix push debarchito ./result
